# Generated by Django 5.0.4 on 2024-04-23 16:24

import django.core.validators
import keep_secrets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', keep_secrets.models.EncryptedTextField()),
                ('code', models.CharField(blank=True, max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='время жизни секрета(в днях)')),
            ],
            options={
                'verbose_name': 'секрет',
                'verbose_name_plural': 'секреты',
            },
        ),
    ]
