# Generated by Django 5.0.4 on 2024-04-23 06:42

import keep_secrets.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep_secrets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='code',
            field=keep_secrets.models.EncryptedTextField(blank=True),
        ),
    ]
