# Generated by Django 5.0.4 on 2024-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_secrets', '0002_alter_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
